import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Comfortaa } from "next/font/google";
import React from "react";

import { AntConfigProvider } from "@/shared/providers";
import { NavBar } from "@/widgets";

import type { Metadata } from "next";

const comfortaa = Comfortaa({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-comfortaa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={comfortaa.className}>
      <body>
        <AntdRegistry>
          <AntConfigProvider>
            <NavBar />
            {children}
          </AntConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
